### ISSUE TITLE
HELP WITH ENV

### ISSUE THREAD

**Issue by MokiMeow** [actuallyakshat/zipit#2]
hey , Ur project looks dope and very useful , wanted to know if there are any constraints on how much u can upload or how many mb of videos and file and  it would be helpful if u provide env .example file and u have any idea why i might be getting the 

 code: 'P2021',
  clientVersion: '5.14.0',
  meta: { modelName: 'Room', table: 'public.Room' }
}
 ⨯ PrismaClientKnownRequestError: 
Invalid `prisma.room.findFirst()` invocation:

The table `public.Room` does not exist in the current database. 
    at async createRoom (./app/_actions/actions.ts:21:34)       
digest: "3878262217"

(i have added the superbase url, key and database url and the environment variable have kept has .env but still getting this

**Comment by actuallyakshat** [comment]
Hey!
Thanks for appreciating my project. Yes, there are constraints for the file upload sizes because I am using the free tier of a media handling service called [uploadthing](https://uploadthing.com/). 

You can customise the file limits by making changes in the app/api/core.ts file. 
![image](https://github.com/actuallyakshat/zipit/assets/120436822/63935aa6-b818-4cdd-9c13-8aeffeb3d72c)

Your issue: `The table public.Room does not exist in the current database.` This usually occurs when you haven't run the Prisma migration command. Make sure you have done that. the command is: `npx prisma migrate dev --name "name of the migration"`

Finally, This is what the .env should look like: 
DATABASE_URL=""
NEXT_PUBLIC_SUPABASE_URL=""
NEXT_PUBLIC_SUPABASE_ANON_KEY =""
UPLOADTHING_SECRET=""
UPLOADTHING_APP_ID=""

you can get the uploadthing key by registering on their website.

**Comment by MokiMeow** [comment]
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  prisma\schema.prisma:7
   | 
 6 |   provider = "postgresql"
 7 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]
(still  getting this even after i put my database url)

its better i explain the steps i did, don't mind new to superbase so little confused 

1- I loaded Ur prj in vs code ran pnpm install then added superbase
2- went to superbase created the project got the key, superbase url and database url 
3- added that to the .env file 
4- the migrate command I don't get it like what name shd we put how does that work , shd we put our prj name or something after that will it initialize the tables in superbase automatically? (this is the part i am stuck and not able to continue

this is my env file
DATABASE_URL="postgresql://postgres.fdqixoehlpenwdrttdda:1.pooler.supabase.com:6543/postgres"
NEXT_PUBLIC_SUPABASE_URL= "https://____________.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJh_______________________"

(some thing is wrong here)?(ofc i have removed the main key and password so ye other than that anything)?would be helpful if u could guide me on this matter. THANK YOU
