### ISSUE TITLE
Prisma gives an error 

### ISSUE THREAD

**Issue by chitrakshbotwala** [actuallyakshat/zipit#3]
the prisma migration gives error that directurl is mentioned in schema but no variable defines it , secondly where should i find realtime db url , secondly it returns P10001 error again and again

**Comment by actuallyakshat** [comment]
You are correct. I recently made some changes to the project where I included a DIRECT_URL in the env but I forgot to update the env example in the description. 

The realtime DB comes from Supabase. 

All you have to do is create a Postgres instance on Supabase, follow their Prisma connection guide in order to migrate the schema, and then finally you need to toggle the 'realtime' switch on for the files table.

P10001 error usually occurs when Prisma is unable to reach the database using the provided url. Adding the DIRECT_URL should fix the issue.

**Comment by chitrakshbotwala** [comment]
Thank you for the reply Akshat , it is a great project I'll be looking forward to contributing to it or trying to add new features , is there anything you're looking to add ?

**Comment by chitrakshbotwala** [comment]
@actuallyakshat remove the migrations folder from the prisma folder as it never lets you migrate the db with that present as it thinks the migrations are done , there  would be no errors and it'll be stuck , so remove that or change the command to 
`npm run prisma:deploy`
